version: '3.8'

volumes:
  pg_data:
  redis_data:

services:
  postgres:
    container_name: postgres
    image: postgres:16.1
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.2
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - ${PGADMIN_PORT}:5050
  redis:
    container_name: redis
    image: redis:7.2.3
    restart: unless-stopped
    ports:
      - ${RD_PORT}:6379
    volumes:
      - redis_data:/data
  zookeeper:
    container_name: zookeeper
    image: debezium/zookeeper:2.4
    restart: unless-stopped
    ports:
      - ${ZKP_CLIENT_PORT}:2181
      - ${ZKP_FOLLOWER_PORT}:2888
      - ${ZKP_LEADER_PORT}:3888
  kafka:
    container_name: kafka
    image: debezium/kafka:2.4
    restart: unless-stopped
    ports:
      - ${KAFKA_PORT}:9092
    environment:
      - ZOOKEEPER_CONNECT=${ZKP_HOST}:${ZKP_CLIENT_PORT}
  kafka-ui:
    container_name: kafka-ui
    restart: unless-stopped
    image: provectuslabs/kafka-ui:latest
    ports:
      - ${KAFKA_UI_PORT}:8080
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
  debezium_connect:
    container_name: debezium_connect
    image: debezium/connect:2.4
    restart: unless-stopped
    ports:
      - ${DEBEZIUM_PORT}:8083
    environment:
      - BOOTSTRAP_SERVERS=${KAFKA_HOST}:${KAFKA_PORT}
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.11.3
    restart: unless-stopped
    ports:
      - ${ES_PORT}:9200
      - ${ES_TRANS_PORT}:9300
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xmx256m -Xms256m
      xpack.security.enabled: false
      discovery.type: single-node
    #
    #  logstash:
    #    container_name: logstash
    #    image: logstash:8.11.3
    #    restart: always
    #    #    volumes:
    #    #      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
    #    #      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    #    ports:
    #      - ${LS_PORT}:5044
    #    #      - 50000:50000/tcp
    #    #      - 50000:50000/udp
    #    #      - 9600:9600
    #    environment:
    #      LS_JAVA_OPTS: -Xms512m -Xmx512m
    #      discovery.seed_hosts: logstash
    #    networks:
    #      - elk
    #    depends_on:
    #      - elasticsearch
    #
  kibana:
    container_name: kibana
    image: kibana:8.11.3
    restart: unless-stopped
    ports:
      - ${KBN_PORT}:5601